// Code generated by MockGen. DO NOT EDIT.
// Source: delete.go

// Package mock_deleter is a generated GoMock package.
package test

import (
	"github.com/golang/mock/gomock"
	"reflect"
)

// MockRestDeleter is a mock of RestDeleter interface
type MockRestDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockRestDeleterMockRecorder
}

// MockRestDeleterMockRecorder is the mock recorder for MockRestDeleter
type MockRestDeleterMockRecorder struct {
	mock *MockRestDeleter
}

// NewMockRestDeleter creates a new mock instance
func NewMockRestDeleter(ctrl *gomock.Controller) *MockRestDeleter {
	mock := &MockRestDeleter{ctrl: ctrl}
	mock.recorder = &MockRestDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRestDeleter) EXPECT() *MockRestDeleterMockRecorder {
	return m.recorder
}

// MakeDeleteRequest mocks base method
func (m *MockRestDeleter) MakeDeleteRequest(url string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeDeleteRequest", url)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeDeleteRequest indicates an expected call of MakeDeleteRequest
func (mr *MockRestDeleterMockRecorder) MakeDeleteRequest(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeDeleteRequest", reflect.TypeOf((*MockRestDeleter)(nil).MakeDeleteRequest), url)
}
